[package]
name = "chumsky"
version = "0.8.0"
description = "A parser library for humans with powerful error recovery"
authors = ["Joshua Barretto <joshua.s.barretto@gmail.com>", "Elijah Hartvigsen <elijah.reed@hartvigsen.xyz"]
repository = "https://github.com/zesterer/chumsky"
license = "MIT"
keywords = ["parser", "combinator", "token", "language", "syntax"]
categories = ["parsing", "text-processing"]
edition = "2018"
exclude = [
    "/misc/*",
	"/benches/*",
]

[features]
default = ["std", "spill-stack"]
# Integrate with the standard library
std = []
# Enable nightly-only features like better compiler diagnostics
nightly = []
# Allows deeper recursion by dynamically spilling stack state on to the heap
spill-stack = ["stacker", "std"]

[dependencies]
# Used if `std` is disabled.
# Provides `ahash` for the corresponding feature as it uses it by default.
# Due to https://github.com/rust-lang/cargo/issues/1839, this can't be optional
hashbrown = "0.12.3"
stacker = { version = "0.1", optional = true }
# Enables regex combinators
regex = { version = "1.5", optional = true }

[dev-dependencies]
ariadne = "0.1.2"
pom = "3.0"
nom = "7.1"
serde_json = { version = "1.0", features = ["preserve_order"] }
criterion = "0.3.5"

[[bench]]
name = "json"
harness = false
